<a href="https://colab.research.google.com/github/NWemphy/MachineLearningB_/blob/main/Selection_features_225314043.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **6C1_Univariate Selection_SelectKBest_Annova**
## **Seleksi 3 fitur**

In [1]:
# Feature Selection with Univariate Statistical Tests
from pandas import read_csv
import pandas as pd
from numpy import set_printoptions
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif
from sklearn.feature_selection import chi2

In [2]:
# Load data
# Data berasal dari 'pima-indians-diabetes.csv' (Kaggle)
# Terdiri dari 9 atribut, 8 atribut independen dan 1 atribut/class tujuan.
# Terdiri dari 768 data observasi yang memiliki 268 positive diabetes, 500 negative diabetes
# data =read_csv('pima-indians-diabetes.csv',names=['Pregnancies','Glucose',
#    'BloodPressure','SkinThickness','Insulin','BMI','DiabetesPedigreeFunction','Age','Class'])
data=read_csv('/content/heart_failure_clinical_records_dataset.csv')
data.head()

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT
0,75.0,0,582,0,20,1,265000.00,1.9,130,1,0,4,1
1,55.0,0,7861,0,38,0,263358.03,1.1,136,1,0,6,1
2,65.0,0,146,0,20,0,162000.00,1.3,129,1,1,7,1
3,50.0,1,111,0,20,0,210000.00,1.9,137,1,0,7,1
4,65.0,1,160,1,20,0,327000.00,2.7,116,0,0,8,1

In [3]:
data.describe()

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT
count,299.000000,299.000000,299.000000,299.000000,299.000000,299.000000,299.000000,299.00000,299.000000,299.000000,299.00000,299.000000,299.00000
mean,60.833893,0.431438,581.839465,0.418060,38.083612,0.351171,263358.029264,1.39388,136.625418,0.648829,0.32107,130.260870,0.32107
std,11.894809,0.496107,970.287881,0.494067,11.834841,0.478136,97804.236869,1.03451,4.412477,0.478136,0.46767,77.614208,0.46767
min,40.000000,0.000000,23.000000,0.000000,14.000000,0.000000,25100.000000,0.50000,113.000000,0.000000,0.00000,4.000000,0.00000
25%,51.000000,0.000000,116.500000,0.000000,30.000000,0.000000,212500.000000,0.90000,134.000000,0.000000,0.00000,73.000000,0.00000
50%,60.000000,0.000000,250.000000,0.000000,38.000000,0.000000,262000.000000,1.10000,137.000000,1.000000,0.00000,115.000000,0.00000
75%,70.000000,1.000000,582.000000,1.000000,45.000000,1.000000,303500.000000,1.40000,140.000000,1.000000,1.00000,203.000000,1.00000
max,95.000000,1.000000,7861.000000,1.000000,80.000000,1.000000,850000.000000,9.40000,148.000000,1.000000,1.00000,285.000000,1.00000

In [4]:
array = data.values
X = array[:,0:8]
Y = array[:,8]

In [5]:
X

array([[7.5000000e+01, 0.0000000e+00, 5.8200000e+02, ..., 1.0000000e+00,
        2.6500000e+05, 1.9000000e+00],
       [5.5000000e+01, 0.0000000e+00, 7.8610000e+03, ..., 0.0000000e+00,
        2.6335803e+05, 1.1000000e+00],
       [6.5000000e+01, 0.0000000e+00, 1.4600000e+02, ..., 0.0000000e+00,
        1.6200000e+05, 1.3000000e+00],
       ...,
       [4.5000000e+01, 0.0000000e+00, 2.0600000e+03, ..., 0.0000000e+00,
        7.4200000e+05, 8.0000000e-01],
       [4.5000000e+01, 0.0000000e+00, 2.4130000e+03, ..., 0.0000000e+00,
        1.4000000e+05, 1.4000000e+00],
       [5.0000000e+01, 0.0000000e+00, 1.9600000e+02, ..., 0.0000000e+00,
        3.9500000e+05, 1.6000000e+00]])

In [6]:
Y

array([130., 136., 129., 137., 116., 132., 137., 131., 138., 133., 131.,
       140., 137., 137., 138., 136., 140., 127., 140., 121., 137., 136.,
       140., 135., 134., 144., 138., 136., 134., 132., 134., 132., 128.,
       138., 140., 134., 134., 145., 137., 142., 134., 136., 139., 134.,
       142., 135., 130., 138., 133., 140., 138., 139., 146., 134., 132.,
       132., 138., 138., 136., 136., 139., 131., 139., 145., 137., 127.,
       136., 140., 142., 135., 140., 139., 132., 137., 134., 139., 140.,
       140., 131., 140., 136., 137., 132., 133., 141., 140., 137., 140.,
       139., 144., 136., 133., 137., 135., 142., 141., 134., 136., 137.,
       140., 141., 137., 144., 140., 143., 138., 137., 138., 133., 142.,
       132., 135., 136., 137., 126., 139., 136., 138., 140., 134., 135.,
       136., 140., 145., 134., 135., 124., 137., 136., 145., 138., 131.,
       137., 145., 137., 137., 137., 130., 136., 138., 134., 140., 132.,
       141., 139., 141., 136., 137., 134., 136., 135., 139., 134., 137.,
       136., 140., 136., 136., 134., 139., 134., 139., 137., 142., 139.,
       135., 133., 134., 138., 133., 136., 140., 145., 139., 137., 138.,
       135., 140., 145., 140., 136., 136., 136., 134., 137., 136., 134.,
       144., 136., 140., 134., 135., 130., 142., 135., 145., 137., 138.,
       134., 113., 137., 136., 138., 136., 137., 136., 141., 136., 141.,
       130., 136., 140., 138., 130., 134., 134., 141., 137., 134., 140.,
       134., 145., 139., 134., 138., 125., 132., 140., 130., 134., 127.,
       134., 137., 137., 137., 137., 148., 132., 136., 137., 139., 136.,
       136., 141., 134., 137., 138., 135., 142., 130., 139., 143., 133.,
       132., 139., 142., 139., 139., 135., 135., 138., 133., 129., 140.,
       141., 140., 134., 140., 140., 132., 130., 134., 133., 140., 137.,
       137., 142., 140., 136., 136., 137., 136., 128., 138., 141., 135.,
       140., 132., 142., 144., 141., 139., 140., 136., 143., 139., 138.,
       140., 136.])

In [7]:
## Dari 8 atribut dipilih 4 atribut yang memiliki score tertinggi
## Feature extraction
test = SelectKBest(score_func=f_classif,k=3)
fit = test.fit(X, Y)

In [8]:
# summarize scores
set_printoptions(precision=3)
print(fit.scores_)
features = fit.transform(X)
# summarize selected features
print(features[0:5,0:4])

[2.157 0.978 0.745 1.407 2.324 0.961 1.296 2.87 ]
[[75.  20.   1.9]
 [55.  38.   1.1]
 [65.  20.   1.3]
 [50.  20.   1.9]
 [65.  20.   2.7]]

In [9]:
## Dari 8 atribut dipilih 4 atribut yang memiliki score tertinggi
## Feature selection
score=pd.Series(fit.scores_)
score.index=data.columns[0:8]
score.sort_values(ascending=False)

serum_creatinine            2.870247
ejection_fraction           2.323938
age                         2.157336
diabetes                    1.406984
platelets                   1.296046
anaemia                     0.977857
high_blood_pressure         0.960653
creatinine_phosphokinase    0.744551
dtype: float64

In [10]:
## Ukuran data features setelah proses feature selection
features.shape

(299, 3)

In [11]:
print(fit.get_feature_names_out(input_features=data.columns[0:8]))

['age' 'ejection_fraction' 'serum_creatinine']

In [12]:
# Mengubah array features yang telah diperoleh ke dalam dataframe
#df=pd.DataFrame(features,columns=['Pregnancies','Glucose','BMI','Age'])
df=pd.DataFrame(features,columns=fit.get_feature_names_out(input_features=data.columns[0:8]))

In [13]:
df.head()

    age  ejection_fraction  serum_creatinine
0  75.0               20.0               1.9
1  55.0               38.0               1.1
2  65.0               20.0               1.3
3  50.0               20.0               1.9
4  65.0               20.0               2.7

## **6C1_Univariate Selection_SelectKBest_Annova**
## **Seleksi 5 fitur**

In [36]:
# Feature Selection with Univariate Statistical Tests
from pandas import read_csv
import pandas as pd
from numpy import set_printoptions
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif
from sklearn.feature_selection import chi2

In [37]:
# Load data
# Data berasal dari 'pima-indians-diabetes.csv' (Kaggle)
# Terdiri dari 9 atribut, 8 atribut independen dan 1 atribut/class tujuan.
# Terdiri dari 768 data observasi yang memiliki 268 positive diabetes, 500 negative diabetes
# data =read_csv('pima-indians-diabetes.csv',names=['Pregnancies','Glucose',
#    'BloodPressure','SkinThickness','Insulin','BMI','DiabetesPedigreeFunction','Age','Class'])
data=read_csv('/content/heart_failure_clinical_records_dataset.csv')
data.head()

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT
0,75.0,0,582,0,20,1,265000.00,1.9,130,1,0,4,1
1,55.0,0,7861,0,38,0,263358.03,1.1,136,1,0,6,1
2,65.0,0,146,0,20,0,162000.00,1.3,129,1,1,7,1
3,50.0,1,111,0,20,0,210000.00,1.9,137,1,0,7,1
4,65.0,1,160,1,20,0,327000.00,2.7,116,0,0,8,1

In [38]:
data.describe()

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT
count,299.000000,299.000000,299.000000,299.000000,299.000000,299.000000,299.000000,299.00000,299.000000,299.000000,299.00000,299.000000,299.00000
mean,60.833893,0.431438,581.839465,0.418060,38.083612,0.351171,263358.029264,1.39388,136.625418,0.648829,0.32107,130.260870,0.32107
std,11.894809,0.496107,970.287881,0.494067,11.834841,0.478136,97804.236869,1.03451,4.412477,0.478136,0.46767,77.614208,0.46767
min,40.000000,0.000000,23.000000,0.000000,14.000000,0.000000,25100.000000,0.50000,113.000000,0.000000,0.00000,4.000000,0.00000
25%,51.000000,0.000000,116.500000,0.000000,30.000000,0.000000,212500.000000,0.90000,134.000000,0.000000,0.00000,73.000000,0.00000
50%,60.000000,0.000000,250.000000,0.000000,38.000000,0.000000,262000.000000,1.10000,137.000000,1.000000,0.00000,115.000000,0.00000
75%,70.000000,1.000000,582.000000,1.000000,45.000000,1.000000,303500.000000,1.40000,140.000000,1.000000,1.00000,203.000000,1.00000
max,95.000000,1.000000,7861.000000,1.000000,80.000000,1.000000,850000.000000,9.40000,148.000000,1.000000,1.00000,285.000000,1.00000

In [39]:
array = data.values
X = array[:,0:8]
Y = array[:,8]

In [40]:
X

array([[7.500e+01, 0.000e+00, 5.820e+02, ..., 1.000e+00, 2.650e+05,
        1.900e+00],
       [5.500e+01, 0.000e+00, 7.861e+03, ..., 0.000e+00, 2.634e+05,
        1.100e+00],
       [6.500e+01, 0.000e+00, 1.460e+02, ..., 0.000e+00, 1.620e+05,
        1.300e+00],
       ...,
       [4.500e+01, 0.000e+00, 2.060e+03, ..., 0.000e+00, 7.420e+05,
        8.000e-01],
       [4.500e+01, 0.000e+00, 2.413e+03, ..., 0.000e+00, 1.400e+05,
        1.400e+00],
       [5.000e+01, 0.000e+00, 1.960e+02, ..., 0.000e+00, 3.950e+05,
        1.600e+00]])

In [41]:
Y

array([130., 136., 129., 137., 116., 132., 137., 131., 138., 133., 131.,
       140., 137., 137., 138., 136., 140., 127., 140., 121., 137., 136.,
       140., 135., 134., 144., 138., 136., 134., 132., 134., 132., 128.,
       138., 140., 134., 134., 145., 137., 142., 134., 136., 139., 134.,
       142., 135., 130., 138., 133., 140., 138., 139., 146., 134., 132.,
       132., 138., 138., 136., 136., 139., 131., 139., 145., 137., 127.,
       136., 140., 142., 135., 140., 139., 132., 137., 134., 139., 140.,
       140., 131., 140., 136., 137., 132., 133., 141., 140., 137., 140.,
       139., 144., 136., 133., 137., 135., 142., 141., 134., 136., 137.,
       140., 141., 137., 144., 140., 143., 138., 137., 138., 133., 142.,
       132., 135., 136., 137., 126., 139., 136., 138., 140., 134., 135.,
       136., 140., 145., 134., 135., 124., 137., 136., 145., 138., 131.,
       137., 145., 137., 137., 137., 130., 136., 138., 134., 140., 132.,
       141., 139., 141., 136., 137., 134., 136., 135., 139., 134., 137.,
       136., 140., 136., 136., 134., 139., 134., 139., 137., 142., 139.,
       135., 133., 134., 138., 133., 136., 140., 145., 139., 137., 138.,
       135., 140., 145., 140., 136., 136., 136., 134., 137., 136., 134.,
       144., 136., 140., 134., 135., 130., 142., 135., 145., 137., 138.,
       134., 113., 137., 136., 138., 136., 137., 136., 141., 136., 141.,
       130., 136., 140., 138., 130., 134., 134., 141., 137., 134., 140.,
       134., 145., 139., 134., 138., 125., 132., 140., 130., 134., 127.,
       134., 137., 137., 137., 137., 148., 132., 136., 137., 139., 136.,
       136., 141., 134., 137., 138., 135., 142., 130., 139., 143., 133.,
       132., 139., 142., 139., 139., 135., 135., 138., 133., 129., 140.,
       141., 140., 134., 140., 140., 132., 130., 134., 133., 140., 137.,
       137., 142., 140., 136., 136., 137., 136., 128., 138., 141., 135.,
       140., 132., 142., 144., 141., 139., 140., 136., 143., 139., 138.,
       140., 136.])

In [42]:
## Dari 8 atribut dipilih 4 atribut yang memiliki score tertinggi
## Feature extraction
test = SelectKBest(score_func=f_classif,k=5)
fit = test.fit(X, Y)

In [43]:
# summarize scores
set_printoptions(precision=5)
print(fit.scores_)
features = fit.transform(X)
# summarize selected features
print(features[0:5,0:4])

[2.15734 0.97786 0.74455 1.40698 2.32394 0.96065 1.29605 2.87025]
[[7.50000e+01 0.00000e+00 2.00000e+01 2.65000e+05]
 [5.50000e+01 0.00000e+00 3.80000e+01 2.63358e+05]
 [6.50000e+01 0.00000e+00 2.00000e+01 1.62000e+05]
 [5.00000e+01 0.00000e+00 2.00000e+01 2.10000e+05]
 [6.50000e+01 1.00000e+00 2.00000e+01 3.27000e+05]]

In [44]:
## Dari 8 atribut dipilih 4 atribut yang memiliki score tertinggi
## Feature selection
score=pd.Series(fit.scores_)
score.index=data.columns[0:8]
score.sort_values(ascending=False)

serum_creatinine            2.870247
ejection_fraction           2.323938
age                         2.157336
diabetes                    1.406984
platelets                   1.296046
anaemia                     0.977857
high_blood_pressure         0.960653
creatinine_phosphokinase    0.744551
dtype: float64

In [45]:
## Ukuran data features setelah proses feature selection
features.shape

(299, 5)

In [46]:
print(fit.get_feature_names_out(input_features=data.columns[0:8]))

['age' 'diabetes' 'ejection_fraction' 'platelets' 'serum_creatinine']

In [47]:
# Mengubah array features yang telah diperoleh ke dalam dataframe
#df=pd.DataFrame(features,columns=['Pregnancies','Glucose','BMI','Age'])
df=pd.DataFrame(features,columns=fit.get_feature_names_out(input_features=data.columns[0:8]))

In [48]:
df.head()

    age  diabetes  ejection_fraction  platelets  serum_creatinine
0  75.0       0.0               20.0  265000.00               1.9
1  55.0       0.0               38.0  263358.03               1.1
2  65.0       0.0               20.0  162000.00               1.3
3  50.0       0.0               20.0  210000.00               1.9
4  65.0       1.0               20.0  327000.00               2.7

## **Chi2**
## **Seleksi 3 Fitur**

In [14]:
## Dari 8 atribut dipilih 4 atribut yang memiliki score tertinggi
## Feature extraction
test = SelectKBest(score_func=chi2,k=3)
fit = test.fit(X, Y)

In [15]:
# summarize scores
set_printoptions(precision=3)
print(fit.scores_)
features = fit.transform(X)
# summarize selected features
print(features[0:5,:])

[1.185e+02 1.453e+01 3.204e+04 2.063e+01 1.992e+02 1.632e+01 1.193e+06
 4.926e+01]
[[5.820e+02 2.000e+01 2.650e+05]
 [7.861e+03 3.800e+01 2.634e+05]
 [1.460e+02 2.000e+01 1.620e+05]
 [1.110e+02 2.000e+01 2.100e+05]
 [1.600e+02 2.000e+01 3.270e+05]]

In [16]:
score=pd.Series(fit.scores_)
score.index=data.columns[0:8]
score.sort_values(ascending=False)

platelets                   1.193129e+06
creatinine_phosphokinase    3.203720e+04
ejection_fraction           1.992098e+02
age                         1.184903e+02
serum_creatinine            4.925965e+01
diabetes                    2.062727e+01
high_blood_pressure         1.631620e+01
anaemia                     1.453186e+01
dtype: float64

In [17]:
features.shape

(299, 3)

In [18]:
print(fit.get_feature_names_out(input_features=data.columns[0:8]))

['creatinine_phosphokinase' 'ejection_fraction' 'platelets']

In [19]:
# Mengubah array features yang telah diperoleh ke dalam dataframe
# df=pd.DataFrame(features,columns=['Glucose','Insuline','BMI','Age'])
df=pd.DataFrame(features,columns=fit.get_feature_names_out(input_features=data.columns[0:8]))

In [20]:
df.head()

   creatinine_phosphokinase  ejection_fraction  platelets
0                     582.0               20.0  265000.00
1                    7861.0               38.0  263358.03
2                     146.0               20.0  162000.00
3                     111.0               20.0  210000.00
4                     160.0               20.0  327000.00

## **Chi2**
## **Seleksi 5 Fitur**

In [52]:
## Dari 8 atribut dipilih 4 atribut yang memiliki score tertinggi
## Feature extraction
test = SelectKBest(score_func=chi2,k=5)
fit = test.fit(X, Y)

In [53]:
# summarize scores
set_printoptions(precision=5)
print(fit.scores_)
features = fit.transform(X)
# summarize selected features
print(features[0:5,:])

[1.18490e+02 1.45319e+01 3.20372e+04 2.06273e+01 1.99210e+02 1.63162e+01
 1.19313e+06 4.92597e+01]
[[7.50000e+01 5.82000e+02 2.00000e+01 2.65000e+05 1.90000e+00]
 [5.50000e+01 7.86100e+03 3.80000e+01 2.63358e+05 1.10000e+00]
 [6.50000e+01 1.46000e+02 2.00000e+01 1.62000e+05 1.30000e+00]
 [5.00000e+01 1.11000e+02 2.00000e+01 2.10000e+05 1.90000e+00]
 [6.50000e+01 1.60000e+02 2.00000e+01 3.27000e+05 2.70000e+00]]

In [54]:
score=pd.Series(fit.scores_)
score.index=data.columns[0:8]
score.sort_values(ascending=False)

platelets                   1.193129e+06
creatinine_phosphokinase    3.203720e+04
ejection_fraction           1.992098e+02
age                         1.184903e+02
serum_creatinine            4.925965e+01
diabetes                    2.062727e+01
high_blood_pressure         1.631620e+01
anaemia                     1.453186e+01
dtype: float64

In [55]:
features.shape

(299, 5)

In [56]:
print(fit.get_feature_names_out(input_features=data.columns[0:8]))

['age' 'creatinine_phosphokinase' 'ejection_fraction' 'platelets'
 'serum_creatinine']

In [ ]:
# Mengubah array features yang telah diperoleh ke dalam dataframe
# df=pd.DataFrame(features,columns=['Glucose','Insuline','BMI','Age'])
df=pd.DataFrame(features,columns=fit.get_feature_names_out(input_features=data.columns[0:8]))

In [ ]:
df.head()

   creatinine_phosphokinase  ejection_fraction  platelets
0                     582.0               20.0  265000.00
1                    7861.0               38.0  263358.03
2                     146.0               20.0  162000.00
3                     111.0               20.0  210000.00
4                     160.0               20.0  327000.00

## **6C3_Feature Selection Using Mutual Information**
## **Seleksi 3 fitur**

In [21]:
# Feature Selection with Univariate Statistical Tests
from pandas import read_csv
import pandas as pd
import numpy as np
from numpy import set_printoptions

In [22]:
data =read_csv('/content/heart_failure_clinical_records_dataset.csv')
data.head()

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT
0,75.0,0,582,0,20,1,265000.00,1.9,130,1,0,4,1
1,55.0,0,7861,0,38,0,263358.03,1.1,136,1,0,6,1
2,65.0,0,146,0,20,0,162000.00,1.3,129,1,1,7,1
3,50.0,1,111,0,20,0,210000.00,1.9,137,1,0,7,1
4,65.0,1,160,1,20,0,327000.00,2.7,116,0,0,8,1

In [23]:
X=data.iloc[:,0:8]
X.head()

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine
0,75.0,0,582,0,20,1,265000.00,1.9
1,55.0,0,7861,0,38,0,263358.03,1.1
2,65.0,0,146,0,20,0,162000.00,1.3
3,50.0,1,111,0,20,0,210000.00,1.9
4,65.0,1,160,1,20,0,327000.00,2.7

In [24]:
Y = data.iloc[:,8]
Y.head()

0    130
1    136
2    129
3    137
4    116
Name: serum_sodium, dtype: int64

In [25]:
from sklearn.feature_selection import mutual_info_classif
mutual_info = mutual_info_classif(X,Y)
mutual_info

array([0.009, 0.   , 0.061, 0.   , 0.088, 0.005, 0.127, 0.097])

In [26]:
mutual_info = pd.Series(mutual_info)
mutual_info.index=X.columns
mutual_info.sort_values(ascending=False)

platelets                   0.126741
serum_creatinine            0.097039
ejection_fraction           0.087704
creatinine_phosphokinase    0.061280
age                         0.008913
high_blood_pressure         0.005179
diabetes                    0.000000
anaemia                     0.000000
dtype: float64

## **6C3_Feature Selection Using Mutual Information**
## **Seleksi 5 fitur**

In [ ]:
# Feature Selection with Univariate Statistical Tests
from pandas import read_csv
import pandas as pd
import numpy as np
from numpy import set_printoptions

In [ ]:
data =read_csv('/content/heart_failure_clinical_records_dataset.csv')
data.head()

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT
0,75.0,0,582,0,20,1,265000.00,1.9,130,1,0,4,1
1,55.0,0,7861,0,38,0,263358.03,1.1,136,1,0,6,1
2,65.0,0,146,0,20,0,162000.00,1.3,129,1,1,7,1
3,50.0,1,111,0,20,0,210000.00,1.9,137,1,0,7,1
4,65.0,1,160,1,20,0,327000.00,2.7,116,0,0,8,1

In [ ]:
X=data.iloc[:,0:8]
X.head()

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine
0,75.0,0,582,0,20,1,265000.00,1.9
1,55.0,0,7861,0,38,0,263358.03,1.1
2,65.0,0,146,0,20,0,162000.00,1.3
3,50.0,1,111,0,20,0,210000.00,1.9
4,65.0,1,160,1,20,0,327000.00,2.7

In [ ]:
Y = data.iloc[:,8]
Y.head()

0    130
1    136
2    129
3    137
4    116
Name: serum_sodium, dtype: int64

In [ ]:
from sklearn.feature_selection import mutual_info_classif
mutual_info = mutual_info_classif(X,Y)
mutual_info

array([0.009, 0.   , 0.061, 0.   , 0.088, 0.005, 0.127, 0.097])

In [ ]:
mutual_info = pd.Series(mutual_info)
mutual_info.index=X.columns
mutual_info.sort_values(ascending=False)

platelets                   0.126741
serum_creatinine            0.097039
ejection_fraction           0.087704
creatinine_phosphokinase    0.061280
age                         0.008913
high_blood_pressure         0.005179
diabetes                    0.000000
anaemia                     0.000000
dtype: float64

## **6D_Recursive Feature Elimination**
## **Logistic Regression**
## **Seleksi 3 fitur**

In [27]:
# Feature Selection with RFE
from pandas import read_csv
#import pandas as pd
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

In [28]:
# Load data
# Data berasal dari 'pima-indians-diabetes.csv' (Kaggle)
# Terdiri dari 9 atribut, 8 atribut independen dan 1 atribut/class tujuan.
# Terdiri dari 768 data observasi yang memiliki 268 positive diabetes, 500 negative diabetes
data =read_csv('/content/heart_failure_clinical_records_dataset.csv')
data.head()

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT
0,75.0,0,582,0,20,1,265000.00,1.9,130,1,0,4,1
1,55.0,0,7861,0,38,0,263358.03,1.1,136,1,0,6,1
2,65.0,0,146,0,20,0,162000.00,1.3,129,1,1,7,1
3,50.0,1,111,0,20,0,210000.00,1.9,137,1,0,7,1
4,65.0,1,160,1,20,0,327000.00,2.7,116,0,0,8,1

In [29]:
data.describe()

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT
count,299.000000,299.000000,299.000000,299.000000,299.000000,299.000000,299.000000,299.00000,299.000000,299.000000,299.00000,299.000000,299.00000
mean,60.833893,0.431438,581.839465,0.418060,38.083612,0.351171,263358.029264,1.39388,136.625418,0.648829,0.32107,130.260870,0.32107
std,11.894809,0.496107,970.287881,0.494067,11.834841,0.478136,97804.236869,1.03451,4.412477,0.478136,0.46767,77.614208,0.46767
min,40.000000,0.000000,23.000000,0.000000,14.000000,0.000000,25100.000000,0.50000,113.000000,0.000000,0.00000,4.000000,0.00000
25%,51.000000,0.000000,116.500000,0.000000,30.000000,0.000000,212500.000000,0.90000,134.000000,0.000000,0.00000,73.000000,0.00000
50%,60.000000,0.000000,250.000000,0.000000,38.000000,0.000000,262000.000000,1.10000,137.000000,1.000000,0.00000,115.000000,0.00000
75%,70.000000,1.000000,582.000000,1.000000,45.000000,1.000000,303500.000000,1.40000,140.000000,1.000000,1.00000,203.000000,1.00000
max,95.000000,1.000000,7861.000000,1.000000,80.000000,1.000000,850000.000000,9.40000,148.000000,1.000000,1.00000,285.000000,1.00000

In [30]:
X

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine
0,75.0,0,582,0,20,1,265000.00,1.9
1,55.0,0,7861,0,38,0,263358.03,1.1
2,65.0,0,146,0,20,0,162000.00,1.3
3,50.0,1,111,0,20,0,210000.00,1.9
4,65.0,1,160,1,20,0,327000.00,2.7
...,...,...,...,...,...,...,...,...
294,62.0,0,61,1,38,1,155000.00,1.1
295,55.0,0,1820,0,38,0,270000.00,1.2
296,45.0,0,2060,1,60,0,742000.00,0.8
297,45.0,0,2413,0,38,0,140000.00,1.4
298,50.0,0,196,0,45,0,395000.00,1.6

In [31]:
Y

0      130
1      136
2      129
3      137
4      116
      ...
294    143
295    139
296    138
297    140
298    136
Name: serum_sodium, Length: 299, dtype: int64

In [32]:
## Feature extraction
model = LogisticRegression(solver='lbfgs')
rfe=RFE(model, n_features_to_select=3, step=1)
##rfe = RFE(model,4,1)
fit = rfe.fit(X,Y)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [33]:
print("Num Features: %d" % fit.n_features_)
print("Selected Features: %s" % fit.support_)
print("Feature Ranking: %s" % fit.ranking_)

Num Features: 3
Selected Features: [ True False  True False False False  True False]
Feature Ranking: [1 5 1 4 2 6 1 3]

In [34]:
print(fit.get_feature_names_out(input_features=data.columns[0:8]))

['age' 'creatinine_phosphokinase' 'platelets']

## **6D_Recursive Feature Elimination**
## **Logistic Regression**
## **Seleksi 5 fitur**

In [57]:
# Feature Selection with RFE
from pandas import read_csv
#import pandas as pd
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

In [58]:
# Load data
# Data berasal dari 'pima-indians-diabetes.csv' (Kaggle)
# Terdiri dari 9 atribut, 8 atribut independen dan 1 atribut/class tujuan.
# Terdiri dari 768 data observasi yang memiliki 268 positive diabetes, 500 negative diabetes
data =read_csv('/content/heart_failure_clinical_records_dataset.csv')
data.head()

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT
0,75.0,0,582,0,20,1,265000.00,1.9,130,1,0,4,1
1,55.0,0,7861,0,38,0,263358.03,1.1,136,1,0,6,1
2,65.0,0,146,0,20,0,162000.00,1.3,129,1,1,7,1
3,50.0,1,111,0,20,0,210000.00,1.9,137,1,0,7,1
4,65.0,1,160,1,20,0,327000.00,2.7,116,0,0,8,1

In [59]:
data.describe()

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT
count,299.000000,299.000000,299.000000,299.000000,299.000000,299.000000,299.000000,299.00000,299.000000,299.000000,299.00000,299.000000,299.00000
mean,60.833893,0.431438,581.839465,0.418060,38.083612,0.351171,263358.029264,1.39388,136.625418,0.648829,0.32107,130.260870,0.32107
std,11.894809,0.496107,970.287881,0.494067,11.834841,0.478136,97804.236869,1.03451,4.412477,0.478136,0.46767,77.614208,0.46767
min,40.000000,0.000000,23.000000,0.000000,14.000000,0.000000,25100.000000,0.50000,113.000000,0.000000,0.00000,4.000000,0.00000
25%,51.000000,0.000000,116.500000,0.000000,30.000000,0.000000,212500.000000,0.90000,134.000000,0.000000,0.00000,73.000000,0.00000
50%,60.000000,0.000000,250.000000,0.000000,38.000000,0.000000,262000.000000,1.10000,137.000000,1.000000,0.00000,115.000000,0.00000
75%,70.000000,1.000000,582.000000,1.000000,45.000000,1.000000,303500.000000,1.40000,140.000000,1.000000,1.00000,203.000000,1.00000
max,95.000000,1.000000,7861.000000,1.000000,80.000000,1.000000,850000.000000,9.40000,148.000000,1.000000,1.00000,285.000000,1.00000

In [60]:
X

array([[7.50000e+01, 0.00000e+00, 5.82000e+02, ..., 1.00000e+00,
        2.65000e+05, 1.90000e+00],
       [5.50000e+01, 0.00000e+00, 7.86100e+03, ..., 0.00000e+00,
        2.63358e+05, 1.10000e+00],
       [6.50000e+01, 0.00000e+00, 1.46000e+02, ..., 0.00000e+00,
        1.62000e+05, 1.30000e+00],
       ...,
       [4.50000e+01, 0.00000e+00, 2.06000e+03, ..., 0.00000e+00,
        7.42000e+05, 8.00000e-01],
       [4.50000e+01, 0.00000e+00, 2.41300e+03, ..., 0.00000e+00,
        1.40000e+05, 1.40000e+00],
       [5.00000e+01, 0.00000e+00, 1.96000e+02, ..., 0.00000e+00,
        3.95000e+05, 1.60000e+00]])

In [61]:
Y

array([130., 136., 129., 137., 116., 132., 137., 131., 138., 133., 131.,
       140., 137., 137., 138., 136., 140., 127., 140., 121., 137., 136.,
       140., 135., 134., 144., 138., 136., 134., 132., 134., 132., 128.,
       138., 140., 134., 134., 145., 137., 142., 134., 136., 139., 134.,
       142., 135., 130., 138., 133., 140., 138., 139., 146., 134., 132.,
       132., 138., 138., 136., 136., 139., 131., 139., 145., 137., 127.,
       136., 140., 142., 135., 140., 139., 132., 137., 134., 139., 140.,
       140., 131., 140., 136., 137., 132., 133., 141., 140., 137., 140.,
       139., 144., 136., 133., 137., 135., 142., 141., 134., 136., 137.,
       140., 141., 137., 144., 140., 143., 138., 137., 138., 133., 142.,
       132., 135., 136., 137., 126., 139., 136., 138., 140., 134., 135.,
       136., 140., 145., 134., 135., 124., 137., 136., 145., 138., 131.,
       137., 145., 137., 137., 137., 130., 136., 138., 134., 140., 132.,
       141., 139., 141., 136., 137., 134., 136., 135., 139., 134., 137.,
       136., 140., 136., 136., 134., 139., 134., 139., 137., 142., 139.,
       135., 133., 134., 138., 133., 136., 140., 145., 139., 137., 138.,
       135., 140., 145., 140., 136., 136., 136., 134., 137., 136., 134.,
       144., 136., 140., 134., 135., 130., 142., 135., 145., 137., 138.,
       134., 113., 137., 136., 138., 136., 137., 136., 141., 136., 141.,
       130., 136., 140., 138., 130., 134., 134., 141., 137., 134., 140.,
       134., 145., 139., 134., 138., 125., 132., 140., 130., 134., 127.,
       134., 137., 137., 137., 137., 148., 132., 136., 137., 139., 136.,
       136., 141., 134., 137., 138., 135., 142., 130., 139., 143., 133.,
       132., 139., 142., 139., 139., 135., 135., 138., 133., 129., 140.,
       141., 140., 134., 140., 140., 132., 130., 134., 133., 140., 137.,
       137., 142., 140., 136., 136., 137., 136., 128., 138., 141., 135.,
       140., 132., 142., 144., 141., 139., 140., 136., 143., 139., 138.,
       140., 136.])

In [62]:
## Feature extraction
model = LogisticRegression(solver='lbfgs')
rfe=RFE(model, n_features_to_select=5, step=1)
##rfe = RFE(model,4,1)
fit = rfe.fit(X,Y)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [63]:
print("Num Features: %d" % fit.n_features_)
print("Selected Features: %s" % fit.support_)
print("Feature Ranking: %s" % fit.ranking_)

Num Features: 5
Selected Features: [ True False  True False  True False  True  True]
Feature Ranking: [1 3 1 2 1 4 1 1]

In [64]:
print(fit.get_feature_names_out(input_features=data.columns[0:8]))

['age' 'creatinine_phosphokinase' 'ejection_fraction' 'platelets'
 'serum_creatinine']

## **RFE - SVR LINEAR**
## **Seleksi 3 Fitur**

In [35]:
from sklearn.feature_selection import RFE
from sklearn.svm import SVR
model = SVR(kernel="linear")
#model = LogisticRegression(solver='lbfgs')
rfe=RFE(model, n_features_to_select=3, step=1)
#rfe = RFE(model,4,1)
fit = rfe.fit(X,Y)

In [ ]:
print("Num Features: %d" % fit.n_features_)
print("Selected Features: %s" % fit.support_)
print("Feature Ranking: %s" % fit.ranking_)

Num Features: 3
Selected Features: [False  True False  True False False False  True]
Feature Ranking: [3 1 5 1 4 2 6 1]

In [ ]:
print(fit.get_feature_names_out(input_features=data.columns[0:8]))

['anaemia' 'diabetes' 'serum_creatinine']

## **RFE - SVR LINEAR**
## **Seleksi 5 Fitur**

In [65]:
from sklearn.feature_selection import RFE
from sklearn.svm import SVR
model = SVR(kernel="linear")
#model = LogisticRegression(solver='lbfgs')
rfe=RFE(model, n_features_to_select=5, step=1)
#rfe = RFE(model,4,1)
fit = rfe.fit(X,Y)

In [66]:
print("Num Features: %d" % fit.n_features_)
print("Selected Features: %s" % fit.support_)
print("Feature Ranking: %s" % fit.ranking_)

Num Features: 5
Selected Features: [ True  True False  True False  True False  True]
Feature Ranking: [1 1 3 1 2 1 4 1]

In [67]:
print(fit.get_feature_names_out(input_features=data.columns[0:8]))

['age' 'anaemia' 'diabetes' 'high_blood_pressure' 'serum_creatinine']

## AKURASI KNN

In [72]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.feature_selection import SelectKBest, f_classif, chi2, RFE
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVR

# Load dataset
data = pd.read_csv("/content/heart_failure_clinical_records_dataset.csv")

# Pisahkan fitur (X) dan target (y)
X = data.drop(columns=["diabetes"])
y = data["diabetes"]

# Standarisasi fitur
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Fungsi evaluasi KNN
def evaluate_knn_with_feature_selection(X, y, selector):
    X_selected = selector.fit_transform(X, y)
    X_train, X_test, y_train, y_test = train_test_split(X_selected, y, test_size=0.2, random_state=42)
    knn = KNeighborsClassifier(n_neighbors=5)
    knn.fit(X_train, y_train)
    y_pred = knn.predict(X_test)
    return accuracy_score(y_test, y_pred)

# Evaluasi berbagai metode seleksi fitur
results = {}

# SelectKBest dengan f_classif
selector_f_classif = SelectKBest(score_func=f_classif, k=3)
results["SelectKBest (f_classif)"] = evaluate_knn_with_feature_selection(X_scaled, y, selector_f_classif)

# SelectKBest dengan f_classif
selector_f_classif = SelectKBest(score_func=f_classif, k=5)
results["SelectKBest (f_classif)"] = evaluate_knn_with_feature_selection(X_scaled, y, selector_f_classif)

# SelectKBest dengan chi2 (tanpa standarisasi)
selector_chi2 = SelectKBest(score_func=chi2, k=3)
results["SelectKBest (chi2)"] = evaluate_knn_with_feature_selection(X, y, selector_chi2)

# SelectKBest dengan chi2 (tanpa standarisasi)
selector_chi2 = SelectKBest(score_func=chi2, k=5)
results["SelectKBest (chi2)"] = evaluate_knn_with_feature_selection(X, y, selector_chi2)

# RFE dengan Logistic Regression sebagai estimator
model = LogisticRegression(max_iter=1000)
selector_rfe_3 = RFE(model, n_features_to_select=3, step=1)
results["RFE (3 features)"] = evaluate_knn_with_feature_selection(X_scaled, y, selector_rfe_3)

model = LogisticRegression(max_iter=1000)
selector_rfe_5 = RFE(model, n_features_to_select=5, step=1)
results["RFE (5 features)"] = evaluate_knn_with_feature_selection(X_scaled, y, selector_rfe_5)

# RFE dengan SVR sebagai estimator
model_svr = SVR(kernel="linear")
selector_rfe_svr_3 = RFE(model_svr, n_features_to_select=3, step=1)
results["RFE (3 features) - SVR"] = evaluate_knn_with_feature_selection(X_scaled, y, selector_rfe_svr_3)

selector_rfe_svr_5 = RFE(model_svr, n_features_to_select=5, step=1)
results["RFE (5 features) - SVR"] = evaluate_knn_with_feature_selection(X_scaled, y, selector_rfe_svr_5)

# Cetak hasil akurasi
sorted_results = sorted(results.items(), key=lambda x: x[1], reverse=True)
print("Ranking Akurasi:")
for rank, (method, accuracy) in enumerate(sorted_results, start=1):
    print(f"{rank}. {method}: {accuracy:.4f}")

Ranking Akurasi:
1. SelectKBest (f_classif): 0.6000
2. RFE (5 features): 0.6000
3. RFE (5 features) - SVR: 0.6000
4. SelectKBest (chi2): 0.5000
5. RFE (3 features) - SVR: 0.5000
6. RFE (3 features): 0.4500